# Generated by Django 5.0.4 on 2026-04-08 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Note', max_length=500)),
                ('content', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'notes_note',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes_permission',
            },
        ),
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_snapshot', models.CharField(max_length=500)),
                ('content_snapshot', models.TextField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='notes.note')),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='notes.note')),
            ],
            options={
                'db_table': 'notes_share_link',
            },
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-updated_at'], name='notes_note_updated_79da70_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['creator', '-updated_at'], name='notes_note_creator_c87ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['is_deleted'], name='notes_note_is_dele_a58d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='notepermission',
            index=models.Index(fields=['user', 'note'], name='notes_permi_user_id_0bc728_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notepermission',
            unique_together={('note', 'user')},
        ),
        migrations.AddIndex(
            model_name='noteversion',
            index=models.Index(fields=['note', '-created_at'], name='notes_versi_note_id_6eddba_idx'),
        ),
    ]
